# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_auto_20161002_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpremium',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='loanpremium',
            name='loan_premium_amount',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loanpremium',
            name='loan_premium_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='loanpremium',
            name='no_of_years',
            field=models.IntegerField(default=20, null=True),
        ),
        migrations.AlterField(
            model_name='loanpremium',
            name='type_duration',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='loanpremium',
            name='type_loan_premium',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='loanpremium',
            name='vat_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
