# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_auto_20161002_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpremium',
            name='end_date',
            field=models.DateField(default=2004),
        ),
    ]
